"""empty message

Revision ID: 3277c156be50
Revises: 
Create Date: 2020-06-23 21:43:16.074603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3277c156be50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('add_compliment_flag', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('add_excuse_flag', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('add_quote_flag', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('add_recurring_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'add_recurring_flag')
    op.drop_column('users', 'add_quote_flag')
    op.drop_column('users', 'add_excuse_flag')
    op.drop_column('users', 'add_compliment_flag')
    # ### end Alembic commands ###
